name: 'Ember Asset Size'
description: 'Find out how much of a change to your asset size a PR will have'
author: 'Chris Manson'
branding:
  icon: 'bar-chart-2'
  color: 'orange'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  update-comments:
    description: 'Optional: Set to true to update existing asset size comment instead of creating a new one each time'
runs:
  using: 'node12'
  main: 'index.js'
